plugins {
    id 'com.android.application'
}

android {
    namespace 'az.qurban.xmdemoaccess'
    compileSdk 35

    defaultConfig {
        applicationId "az.qurban.xmdemoaccess"
        minSdk 24
        targetSdk 35
        versionCode 7
        versionName "0.7-gold-screenshot-matched"
    }
}
